### ISSUE TITLE
Error in adding to gradle

### ISSUE THREAD

**Issue by DoktorBog** [Meetic/MaryPopup#2]
Could not find com.meetic.marypopup:marypopup:1.0.0.

**Comment by NikitaDmitrenko** [comment]
Yeah , have the same issue , please fix it

**Comment by DoktorBog** [comment]
Yes, I found the cause of the error:
Need to add 
`repositories {
        maven { url  "http://dl.bintray.com/meetic-android/maven" }`

**Comment by NikitaDmitrenko** [comment]
Thank you , it helps me , like a god !

**Comment by yujloup** [comment]
Readme has been updated. Thx for the feedback
